CAMERA_INDEX = 0

WIDTH = 1280
HEIGHT = 720
FPS = 30
USE_THREADED_CAPTURE = True

MIRROR_CAMERA = True
WINDOW_NAME = "Prism Kenz Preview"

BEAUTY_ENABLED = False
BEAUTY_STRENGTH = 0.0
BEAUTY_MODE = "off"  # off, fast, quality

BACKGROUND_ENABLED = True
BACKGROUND_MODE = "image"
BACKGROUND_IMAGE_PATH = "assets/backgrounds/bg.jpg"
BACKGROUND_BLUR_KERNEL = 15
BLUR_WORK_WIDTH = 320
BLUR_WORK_HEIGHT = 180

SEGMENTATION_BACKEND = "rvm"
SEGMENTATION_THRESHOLD = 0.55

RVM_MODEL = "mobilenetv3"
RVM_DEVICE = "cuda"
RVM_DOWNSAMPLE_RATIO = 0.20
RVM_INFERENCE_WIDTH = 640
RVM_INFERENCE_HEIGHT = 360
RVM_PROCESS_EVERY_N_FRAMES = 2
# Ative depois de validar o pipeline. Alguns builds/modelos RVM podem encerrar
# o processo nativamente durante a primeira inferencia FP16.
USE_FP16 = False
RVM_TORCH_THREADS = 6
RVM_ALPHA_SHIFT = 0.0

MASK_BLUR_KERNEL = 1
MASK_FEATHER_KERNEL = 3

# Performance logging
FPS_LOG_INTERVAL_SECONDS = 2.0
SHOW_PERFORMANCE_LOGS = True
SHOW_FPS_OVERLAY = True

# Virtual camera
VIRTUAL_CAMERA_ENABLED = True
VIRTUAL_CAMERA_FPS = 30
VIRTUAL_CAMERA_BACKEND = None
VIRTUAL_CAMERA_FMT = "BGR"
